#!/usr/bin/env bash

COMPONENT_NAME=`basename $PWD`;
COMPONENT_NAME_VIEW=$COMPONENT_NAME"View";
cat >> 'index.js'<< EOF
export {$COMPONENT_NAME} from './$COMPONENT_NAME';

EOF
cat >> "$COMPONENT_NAME.js"<<EOF
import React, { Component, PropTypes } from 'react';
import PureRender from 'pure-render-decorator';
import {connect} from 'react-redux';

import {$COMPONENT_NAME_VIEW} from './$COMPONENT_NAME_VIEW';

const mapDispatchToProps = {
};

function mapStateToProps(state) {
  return {};
}

@connect(mapStateToProps, mapDispatchToProps)
@PureRender
export class $COMPONENT_NAME extends Component {
  render () {
    return (
      <$COMPONENT_NAME_VIEW/>
    );
  }
}

EOF

cat >> "$COMPONENT_NAME.scss" << EOF
.view{
}

EOF

cat >> "$COMPONENT_NAME_VIEW.js" << EOF
import React, { Component, PropTypes } from 'react';
import PureRender from 'pure-render-decorator';

import styles from './$COMPONENT_NAME.scss';

@PureRender
export class $COMPONENT_NAME_VIEW extends Component {
  render () {
    return (
      <div className={styles.view}></div>
    );
  }
}

EOF
