#!/usr/bin/env bash

COMPONENT_NAME=`basename $PWD`;
. ~/bin/templates/smart
. ~/bin/templates/index
. ~/bin/templates/dump
. ~/bin/templates/scss
CV=$COMPONENT_NAME"View"

case "$1" in
#smart component
    "s")
        index $COMPONENT_NAME
        dump $CV
        smart $COMPONENT_NAME $CV
        scss $COMPONENT_NAME
    ;;
# dump component
    "d")
        index $COMPONENT_NAME
        dump $COMPONENT_NAME
    ;;
#dump component with styles
    "ds")
        index $COMPONENT_NAME
        dump $COMPONENT_NAME
        scss $COMPONENT_NAME
    ;;
    *) echo "unknown command";;
esac
