#!/usr/bin/env bash

function dump() {
    cat >> "$1.js" << EOF
import React, { Component, PropTypes } from 'react';
import PureRender from 'pure-render-decorator';

@PureRender
export class $1 extends Component {
  render () {
    return (
      <div></div>
    );
  }
}

EOF
}