#!/usr/bin/env bash

function smart() {
   cat >> "$1.js" << EOF
import React, { Component, PropTypes } from 'react';
import PureRender from 'pure-render-decorator';
import {connect} from 'react-redux';

import {$2} from './$2';

const mapDispatchToProps = {
};

function mapStateToProps(state) {
  return {};
}

@connect(mapStateToProps, mapDispatchToProps)
@PureRender
export class $1 extends Component {
  render () {
    return (
      <$2/>
    );
  }
}

EOF
}